default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Sandhya1325
  host: localhost

development:
  <<: *default
  database: Rails_Ruby_development

test:
  <<: *default
  database: Rails_Ruby_test

production:
  <<: *default
  database: Rails_Ruby_production
